# Generated by Django 6.0 on 2026-08-01 14:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('species', models.CharField(choices=[('Bovin', 'Bovin'), ('Ovin', 'Ovin'), ('Caprin', 'Caprin'), ('Porcin', 'Porcin'), ('Équin', 'Équin'), ('Lapin', 'Lapin')], max_length=30)),
                ('breed', models.CharField(max_length=100)),
                ('sex', models.CharField(choices=[('Mâle', 'Mâle'), ('Femelle', 'Femelle')], max_length=20)),
                ('age', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('health_status', models.CharField(choices=[('En bonne santé', 'En bonne santé'), ('À vacciner', 'À vacciner'), ('Traitement en cours', 'Traitement en cours'), ('Malade', 'Malade')], default='En bonne santé', max_length=30)),
                ('vaccinations', models.TextField(blank=True)),
                ('treatments', models.TextField(blank=True)),
                ('photo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_type', models.CharField(max_length=100)),
                ('planting_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('En croissance', 'En croissance'), ('Mûr', 'Mûr'), ('Récolté', 'Récolté'), ('Problème', 'Problème')], default='En croissance', max_length=30)),
                ('estimated_production', models.CharField(blank=True, max_length=100)),
                ('photo', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Culture',
                'verbose_name_plural': 'Cultures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(max_length=100)),
                ('pond', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('feeding', models.CharField(blank=True, max_length=100)),
                ('growth', models.CharField(blank=True, max_length=100)),
                ('water_quality', models.CharField(blank=True, max_length=100)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('harvest_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Poisson',
                'verbose_name_plural': 'Poissons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incubator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('incubation_date', models.DateField()),
                ('hatch_date', models.DateField(blank=True, null=True)),
                ('eggs_count', models.IntegerField(default=0)),
                ('fertile_eggs', models.IntegerField(default=0)),
                ('infertile_eggs', models.IntegerField(default=0)),
                ('chicks_hatched', models.IntegerField(default=0)),
                ('status', models.CharField(default='En incubation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Couveuse',
                'verbose_name_plural': 'Couveuses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('vaccination', 'Vaccination'), ('harvest', 'Récolte'), ('hatching', 'Éclosion'), ('birth', 'Naissance'), ('disease', 'Maladie'), ('fish_harvest', 'Récolte des poissons')], max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('location', models.CharField(max_length=150)),
                ('soil_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Parcelle',
                'verbose_name_plural': 'Parcelles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Poultry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(choices=[('Poulet', 'Poulet'), ('Poule pondeuse', 'Poule pondeuse'), ('Canard', 'Canard'), ('Dinde', 'Dinde'), ('Pintade', 'Pintade')], max_length=30)),
                ('entries', models.IntegerField(default=0)),
                ('exits', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('feed', models.CharField(blank=True, max_length=100)),
                ('egg_production', models.CharField(blank=True, max_length=100)),
                ('vaccination', models.CharField(blank=True, max_length=100)),
                ('growth', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Volaille',
                'verbose_name_plural': 'Volailles',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Saison',
                'verbose_name_plural': 'Saisons',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest_date', models.DateField()),
                ('quantity', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harvests', to='gestion.crop')),
            ],
            options={
                'verbose_name': 'Récolte',
                'verbose_name_plural': 'Récoltes',
                'ordering': ['-harvest_date'],
            },
        ),
        migrations.AddField(
            model_name='crop',
            name='plots',
            field=models.ManyToManyField(blank=True, related_name='crops', to='gestion.plot'),
        ),
        migrations.AddField(
            model_name='crop',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crops', to='gestion.season'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('farmer', 'Agriculteur / Éleveur')], default='farmer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
    ]
