# Generated by Django 4.2.30 on 2026-08-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incubator',
            options={'ordering': ['-created_at'], 'verbose_name': 'Incubation', 'verbose_name_plural': 'Incubations'},
        ),
        migrations.RemoveField(
            model_name='incubator',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='incubator',
            name='chicks_hatched',
        ),
        migrations.RemoveField(
            model_name='incubator',
            name='fertile_eggs',
        ),
        migrations.RemoveField(
            model_name='incubator',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='incubator',
            name='infertile_eggs',
        ),
        migrations.RemoveField(
            model_name='incubator',
            name='name',
        ),
        migrations.RemoveField(
            model_name='incubator',
            name='temperature',
        ),
        migrations.AddField(
            model_name='incubator',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Remarques'),
        ),
        migrations.AlterField(
            model_name='incubator',
            name='eggs_count',
            field=models.IntegerField(verbose_name="Nombre d'œufs incubés"),
        ),
        migrations.AlterField(
            model_name='incubator',
            name='hatch_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'éclosion prévue"),
        ),
        migrations.AlterField(
            model_name='incubator',
            name='incubation_date',
            field=models.DateField(verbose_name="Date d'incubation"),
        ),
        migrations.AlterField(
            model_name='incubator',
            name='status',
            field=models.CharField(default='En incubation', max_length=50, verbose_name='Statut'),
        ),
    ]
