# Generated by Django 4.2.30 on 2026-08-14 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_alter_incubator_options_remove_incubator_capacity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fish',
        ),
    ]
