# Generated by Django 4.2.30 on 2026-08-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_fish_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('vaccination', 'Vaccination'), ('harvest', 'Récolte'), ('hatching', 'Éclosion'), ('birth', 'Naissance'), ('disease', 'Maladie')], max_length=20),
        ),
    ]
